Fix type mismatch (compile time, on MSVC, see below) on librdf_world_set_logger call. librdf_log_func is defined as: typedef int (REDLAND_CALLBACK_STDCALL *librdf_log_func)(void *user_data, librdf_log_message *message);
error C2664: 'librdf_world_set_logger' : cannot convert parameter 3 from 'int (__cdecl *)(void *,librdf_log_message *)' to 'librdf_log_func'